packages:
  - 'packages/*'
  - 'integrations/*'
  - 'examples/angular/*'
  - 'examples/lit/*'
  - 'examples/react/*'
  - 'examples/solid/*'
  - 'examples/svelte/*'
  - 'examples/vue/*'
  - '!examples/vue/2*'
  - '!examples/vue/nuxt*'
